// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFCbgQad7plOTM5xeiRIxYex2IlvrAdFE',
    appId: '1:856676434773:web:84ba0bf512af22920325dc',
    messagingSenderId: '856676434773',
    projectId: 'stockmateproject',
    authDomain: 'stockmateproject.firebaseapp.com',
    storageBucket: 'stockmateproject.appspot.com',
    measurementId: 'G-EV7FY1PNXJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY25ZmwDenbCMfWbXvBtugOwlnlKKqLF4',
    appId: '1:856676434773:android:47eb9646794a258f0325dc',
    messagingSenderId: '856676434773',
    projectId: 'stockmateproject',
    storageBucket: 'stockmateproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBENlbPlM7DqaDlWJz1h4HPd5D70nBkM30',
    appId: '1:856676434773:ios:a96a00a3bdf7a8fc0325dc',
    messagingSenderId: '856676434773',
    projectId: 'stockmateproject',
    storageBucket: 'stockmateproject.appspot.com',
    iosClientId: '856676434773-kabbfkhh5fq4vev5j79genfkof28632u.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBENlbPlM7DqaDlWJz1h4HPd5D70nBkM30',
    appId: '1:856676434773:ios:792d5059db1e0d940325dc',
    messagingSenderId: '856676434773',
    projectId: 'stockmateproject',
    storageBucket: 'stockmateproject.appspot.com',
    iosClientId: '856676434773-alst5aa9b9ufstvctbh03iar86kms1q4.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockmate.RunnerTests',
  );
}
